In [58]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

In [59]:
df = pd.read_csv('C:\Edu\coding\python\Scikit Learn\covid_toy.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\E'
<>:1: SyntaxWarning: invalid escape sequence '\E'
C:\Users\User\AppData\Local\Temp\ipykernel_1444\525473553.py:1: SyntaxWarning: invalid escape sequence '\E'
  df = pd.read_csv('C:\Edu\coding\python\Scikit Learn\covid_toy.csv')

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [60]:
X = df.drop(columns=['has_covid'])
y = df['has_covid']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [61]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [62]:
si = SimpleImputer()

X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever

array([[ 99.],
       [ 98.],
       [100.],
       [103.],
       [101.],
       [ 98.],
       [101.],
       [ 98.],
       [101.],
       [101.],
       [101.],
       [100.],
       [104.],
       [102.],
       [102.],
       [103.],
       [101.],
       [103.],
       [ 98.],
       [101.],
       [103.],
       [102.],
       [101.],
       [ 98.],
       [101.],
       [100.],
       [104.],
       [101.],
       [ 99.],
       [102.],
       [102.],
       [104.],
       [101.],
       [102.],
       [104.],
       [ 99.],
       [102.],
       [104.],
       [101.],
       [100.],
       [100.],
       [ 99.],
       [ 99.],
       [101.],
       [100.],
       [104.],
       [104.],
       [ 99.],
       [ 98.],
       [104.],
       [101.],
       [ 98.],
       [101.],
       [102.],
       [100.],
       [104.],
       [ 98.],
       [ 98.],
       [102.],
       [104.],
       [ 98.],
       [103.],
       [ 98.],
       [104.],
       [104.],
       [103.],
       [102.],
       [101.],
       [104.],
       [103.],
       [101.],
       [ 99.],
       [ 99.],
       [ 99.],
       [101.],
       [101.],
       [101.],
       [100.],
       [100.],
       [ 98.]])

In [63]:
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])

X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.]])

In [64]:
ohe = OneHotEncoder(drop='first')

X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])
X_test_gender_city = ohe.fit_transform(X_test[['gender', 'city']])

X_train_gender_city

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 87 stored elements and shape (80, 4)>

In [65]:
X_train_age = X_train.drop(columns=['gender', 'fever', 'cough', 'city']).values
X_test_age = X_test.drop(columns=['gender', 'fever', 'cough', 'city']).values

X_train_age

array([[25],
       [64],
       [27],
       [73],
       [68],
       [ 5],
       [75],
       [31],
       [14],
       [79],
       [81],
       [10],
       [18],
       [33],
       [82],
       [46],
       [20],
       [16],
       [69],
       [23],
       [50],
       [69],
       [64],
       [83],
       [34],
       [27],
       [44],
       [38],
       [65],
       [ 5],
       [20],
       [16],
       [84],
       [74],
       [42],
       [59],
       [82],
       [17],
       [42],
       [19],
       [ 5],
       [65],
       [22],
       [19],
       [19],
       [12],
       [51],
       [60],
       [40],
       [ 6],
       [71],
       [26],
       [51],
       [24],
       [80],
       [51],
       [23],
       [81],
       [64],
       [75],
       [80],
       [48],
       [10],
       [54],
       [56],
       [60],
       [49],
       [47],
       [34],
       [70],
       [42],
       [14],
       [49],
       [66],
       [19],
       [34],
       [83],
       [55],
       [11],
       [34]], dtype=int64)

In [68]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(drop='first'), ['gender', 'city'])
], remainder='passthrough')

In [69]:
transformer.fit_transform(X_train)

array([[ 99.,   1.,   0.,   0.,   1.,   0.,  25.],
       [ 98.,   0.,   0.,   0.,   0.,   0.,  64.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [101.,   1.,   0.,   1.,   0.,   0.,  68.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,   5.],
       [101.,   0.,   0.,   1.,   0.,   0.,  75.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  31.],
       [101.,   1.,   1.,   0.,   0.,   0.,  14.],
       [101.,   1.,   1.,   0.,   1.,   0.,  79.],
       [101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [100.,   0.,   1.,   0.,   0.,   0.,  10.],
       [104.,   0.,   0.,   0.,   0.,   0.,  18.],
       [102.,   1.,   0.,   1.,   0.,   0.,  33.],
       [102.,   1.,   0.,   0.,   0.,   0.,  82.],
       [103.,   1.,   1.,   0.,   0.,   0.,  46.],
       [101.,   1.,   0.,   0.,   0.,   1.,  20.],
       [103.,   0.,   0.,   0.,   0.,   0.,  16.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  69.],
       [101.,   0.,   1.,   0.,   0.,   1.,  23.],
       [103.,   0.,   0.,   0.,   1.,   0.,  50.],
       [102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [101.,   0.,   0.,   1.,   0.,   0.,  64.],
       [ 98.,   0.,   1.,   1.,   0.,   0.,  83.],
       [101.,   1.,   0.,   1.,   0.,   0.,  34.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [104.,   0.,   1.,   0.,   0.,   1.,  44.],
       [101.,   0.,   0.,   0.,   0.,   0.,  38.],
       [ 99.,   0.,   1.,   1.,   0.,   0.,  65.],
       [102.,   0.,   1.,   0.,   1.,   0.,   5.],
       [102.,   1.,   1.,   1.,   0.,   0.,  20.],
       [104.,   0.,   1.,   0.,   1.,   0.,  16.],
       [101.,   0.,   0.,   0.,   0.,   0.,  84.],
       [102.,   0.,   1.,   0.,   0.,   1.,  74.],
       [104.,   0.,   1.,   0.,   0.,   1.,  42.],
       [ 99.,   1.,   0.,   1.,   0.,   0.,  59.],
       [102.,   1.,   0.,   0.,   1.,   0.,  82.],
       [104.,   0.,   0.,   0.,   1.,   0.,  17.],
       [101.,   0.,   1.,   1.,   0.,   0.,  42.],
       [100.,   0.,   0.,   0.,   1.,   0.,  19.],
       [100.,   0.,   0.,   0.,   1.,   0.,   5.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  65.],
       [ 99.,   0.,   0.,   0.,   0.,   0.,  22.],
       [101.,   0.,   1.,   1.,   0.,   0.,  19.],
       [100.,   1.,   0.,   0.,   0.,   0.,  19.],
       [104.,   0.,   0.,   0.,   0.,   0.,  12.],
       [104.,   0.,   1.,   0.,   0.,   0.,  51.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  60.],
       [ 98.,   1.,   0.,   1.,   0.,   0.,  40.],
       [104.,   0.,   0.,   0.,   1.,   0.,   6.],
       [101.,   1.,   1.,   0.,   1.,   0.,  71.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  26.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [102.,   1.,   0.,   0.,   0.,   0.,  24.],
       [100.,   0.,   1.,   0.,   0.,   0.,  80.],
       [104.,   0.,   1.,   0.,   1.,   0.,  51.],
       [ 98.,   1.,   1.,   0.,   0.,   1.,  23.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  81.],
       [102.,   0.,   1.,   0.,   0.,   0.,  64.],
       [104.,   1.,   0.,   1.,   0.,   0.,  75.],
       [ 98.,   0.,   0.,   1.,   0.,   0.,  80.],
       [103.,   0.,   0.,   0.,   1.,   0.,  48.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  10.],
       [104.,   1.,   0.,   0.,   1.,   0.,  54.],
       [104.,   1.,   0.,   0.,   0.,   0.,  56.],
       [103.,   0.,   1.,   0.,   1.,   0.,  60.],
       [102.,   0.,   0.,   1.,   0.,   0.,  49.],
       [101.,   1.,   1.,   0.,   0.,   0.,  47.],
       [104.,   1.,   0.,   1.,   0.,   0.,  34.],
       [103.,   1.,   1.,   0.,   1.,   0.,  70.],
       [101.,   1.,   0.,   0.,   0.,   0.,  42.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  14.],
       [ 99.,   1.,   0.,   0.,   0.,   0.,  49.],
       [ 99.,   1.,   1.,   0.,   0.,   0.,  66.],
       [101.,   0.,   0.,   0.,   0.,   1.,  19.],
       [101.,   1.,   0.,   0.,   0.,   1.,  34.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [100.,   0.,   1.,   0.,   1.,   0.,  55.],
       [100.,   1.,   0.,   0.,   1.,   0.,  11.],
       [ 98.,   1.,   1.,   0.,   1.,   0.,  34.]])

In [47]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]